### ISSUE TITLE
ModuleNotFoundError: No module named 'rx.subjects'

### ISSUE THREAD

**Issue by akinniyi** [jaydenwindle/graphene-subscriptions#12]
Running python manage.py runserver triggers an error with the traceback below. Looks like subjects is not present in Rx==3.0.1

`Traceback (most recent call last):
  File "/home/niyi/.virtualenvs/nextech/lib/python3.6/site-packages/channels/routing.py", line 29, in get_default_application
    module = importlib.import_module(path)
  File "/home/niyi/.virtualenvs/nextech/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  .......
    from rx.subjects import Subject
ModuleNotFoundError: No module named 'rx.subjects'`

**Comment by jaydenwindle** [comment]
Good catch @akinniyi!

Right now, this library is dependent on `graphene-django` v2 which still uses the old `graphql-core`. `graphql-core` is only compatible with [`rx>=1.6,<2`](https://github.com/graphql-python/graphql-core/blob/fe703f0d176c78b205d2abf929193f1e910fe4a0/setup.py#L24), so we won't be able to use this library with `rx>=2` until `graphene-django` v3 is released 😿.

We should probably version-lock `rx` to `1.6.1`, which will cause pip to throw an error on install when you try to use this library with a later version of `rx`.

Would you be interested in opening a PR for this?

**Comment by akinniyi** [comment]
It'll be my first public PR so yes!

**Comment by akinniyi** [comment]
Thanks for this project by the way

**Comment by jaydenwindle** [comment]
Amazing! You're very welcome 😊
